import "./globals.css";

export const metadata = {
  title: "Pokemon Battle Sequence",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen flex items-center justify-center">
        {children}
      </body>
    </html>
  );
}
